services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.3
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  kafka:
    image: confluentinc/cp-kafka:7.4.3
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    networks:
      - backend

  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6378:6379"
    restart: always
    networks:
      - backend

  fastapi:
    image: shee9812/backend_ai:latest
    container_name: fastapi
    ports:
      - "8000"
    networks:
      - backend

  gateway:
    image: ${DOCKER_USERNAME}/aivle-gateway:latest
    container_name: gateway
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - backend

  auth-service:
    image: ${DOCKER_USERNAME}/aivle-auth:latest
    container_name: auth-service
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

  store-service:
    image: ${DOCKER_USERNAME}/aivle-store:latest
    container_name: store-service
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

  shorts-service:
    image: ${DOCKER_USERNAME}/aivle-shorts:latest
    container_name: shorts-service
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

  content-service:
    image: ${DOCKER_USERNAME}/aivle-content:latest
    container_name: content-service
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CLOUDFRONT_PRIVATE_KEY=${CLOUDFRONT_PRIVATE_KEY}
    networks:
      - backend

  sns-service:
    image: ${DOCKER_USERNAME}/aivle-sns:latest
    container_name: sns-service
    depends_on:
      - kafka
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - CLOUDFRONT_PRIVATE_KEY=${CLOUDFRONT_PRIVATE_KEY}
    networks:
      - backend

  analytics-service:
    image: ${DOCKER_USERNAME}/aivle-analytics:latest
    container_name: analytics-service
    depends_on:
      - kafka
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - TZ=Asia/Seoul
    networks:
      - backend

networks:
  backend:
    driver: bridge
