services:
  gateway:
    image: ${DOCKER_USERNAME}/aivle-gateway:latest
    container_name: gateway
    depends_on:
      - auth-service
      - store-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - backend

  auth-service:
    image: ${DOCKER_USERNAME}/aivle-auth:latest
    container_name: auth-service
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

  store-service:
    image: ${DOCKER_USERNAME}/aivle-store:latest
    container_name: store-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge