services:
  gateway:
    image: aivle-gateway:latest
    container_name: gateway
    depends_on:
      - auth-service
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8080:8080"
    networks:
      - backend

  auth-service:
    image: aivle-auth:latest
    container_name: auth-service
    depends_on:
      - redis
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - "8081:8080"
    networks:
      - backend

  redis:
    image: redis:7.2
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend

networks:
  backend:
    driver: bridge