name: MSA CI/CD with paths-filter

on:
  push:
    branches: [ "release" ]

jobs:
  filter:
    runs-on: ubuntu-latest
    outputs:
      compose: ${{ steps.filter.outputs.compose }}
      gateway: ${{ steps.filter.outputs.gateway }}
      auth: ${{ steps.filter.outputs.auth }}
      store: ${{ steps.filter.outputs.store }}
      shorts: ${{ steps.filter.outputs.shorts }}
    steps:
      - uses: actions/checkout@v4

      - name: Check changed paths
        id: filter
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            compose:
              - 'docker-compose.prod.yml'
            gateway:
              - 'gateway/**'
            auth:
              - 'auth-service/**'
            store:
              - 'store-service/**'
            shorts:
              - 'shorts-service/**'

  upload-compose:
    needs: filter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare prod compose
        run: cp docker-compose.prod.yml docker-compose.yml

      - name: Upload docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AWS_SECRET_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          source: "docker-compose.yml"
          target: "/home/ubuntu/deploy/"

  build-and-deploy-gateway:
    needs: [ filter, upload-compose ]
    if: ${{ needs.filter.outputs.gateway == 'true' || needs.filter.outputs.compose == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml for gateway
        run: |
          mkdir -p ./gateway/src/main/resources
          cat <<EOF > ./gateway/src/main/resources/application.yml
          ${{ secrets.APPLICATION_YML_GATEWAY }}
          EOF
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build gateway JAR
        run: ./gradlew :gateway:clean :gateway:build

      - name: Docker build & push (gateway)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aivle-gateway:latest ./gateway
          docker push ${{ secrets.DOCKER_USERNAME }}/aivle-gateway:latest

      - name: Deploy gateway to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SECRET_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /home/ubuntu/deploy/
            tmp_env=$(mktemp)
            grep -v '^DOCKER_USERNAME=' .env > "$tmp_env" || true
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> "$tmp_env"
            mv "$tmp_env" .env
            docker compose pull gateway
            docker compose up -d gateway
            docker image prune -f || true

  build-and-deploy-auth-service:
    needs: [ filter, upload-compose ]
    if: ${{ needs.filter.outputs.auth == 'true' || needs.filter.outputs.compose == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml for auth-service
        run: |
          mkdir -p ./auth-service/src/main/resources
          cat <<EOF > ./auth-service/src/main/resources/application.yml
          ${{ secrets.APPLICATION_YML_AUTH }}
          EOF
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build auth-service JAR
        run: ./gradlew :auth-service:clean :auth-service:build

      - name: Docker build & push (auth-service)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aivle-auth:latest ./auth-service
          docker push ${{ secrets.DOCKER_USERNAME }}/aivle-auth:latest

      - name: Deploy auth-service to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SECRET_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /home/ubuntu/deploy/
            tmp_env=$(mktemp)
            grep -v '^DOCKER_USERNAME=' .env > "$tmp_env" || true
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> "$tmp_env"
            mv "$tmp_env" .env
            docker compose pull auth-service
            docker compose up -d auth-service
            docker image prune -f || true

  build-and-deploy-store-service:
    needs: [ filter, upload-compose ]
    if: ${{ needs.filter.outputs.store == 'true' || needs.filter.outputs.compose == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml for store-service
        run: |
          mkdir -p ./store-service/src/main/resources
          cat <<EOF > ./store-service/src/main/resources/application.yml
          ${{ secrets.APPLICATION_YML_STORE }}
          EOF
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build store-service JAR
        run: ./gradlew :store-service:clean :store-service:build

      - name: Docker build & push (store-service)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aivle-store:latest ./store-service
          docker push ${{ secrets.DOCKER_USERNAME }}/aivle-store:latest

      - name: Deploy store-service to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SECRET_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /home/ubuntu/deploy/
            tmp_env=$(mktemp)
            grep -v '^DOCKER_USERNAME=' .env > "$tmp_env" || true
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> "$tmp_env"
            mv "$tmp_env" .env
            docker compose pull store-service
            docker compose up -d store-service
            docker image prune -f || true

  build-and-deploy-shorts-service:
    needs: [ filter, upload-compose ]
    if: ${{ needs.filter.outputs.shorts == 'true' || needs.filter.outputs.compose == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Create application.yml for shorts-service
        run: |
          mkdir -p ./shorts-service/src/main/resources
          cat <<EOF > ./shorts-service/src/main/resources/application.yml
          ${{ secrets.APPLICATION_YML_SHORTS }}
          EOF
        shell: bash

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build shorts-service JAR
        run: ./gradlew :shorts-service:clean :shorts-service:build

      - name: Docker build & push (shorts-service)
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/aivle-shorts:latest ./shorts-service
          docker push ${{ secrets.DOCKER_USERNAME }}/aivle-shorts:latest

      - name: Deploy shorts-service to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_SECRET_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          script: |
            cd /home/ubuntu/deploy/
            tmp_env=$(mktemp)
            grep -v '^DOCKER_USERNAME=' .env > "$tmp_env" || true
            echo "DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}" >> "$tmp_env"
            mv "$tmp_env" .env
            docker compose pull shorts-service
            docker compose up -d shorts-service
            docker image prune -f || true