name: MSA Secret Debug All Methods

on:
  push:
    branches: [ "feature/cicd" ]

jobs:
  debug-gateway-secret:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1. echo로 바로 출력
      - name: echo secret value
        run: |
          echo "=== echo (double quote) ==="
          echo "${{ secrets.APPLICATION_YML_GATEWAY }}"
          echo "=== echo (single quote) ==="
          echo '${{ secrets.APPLICATION_YML_GATEWAY }}'
          echo "=== END OF ECHO ==="
        shell: bash

      # 2. printf로 바로 출력
      - name: printf secret value
        run: |
          echo "=== printf (double quote) ==="
          printf "%s\n" "${{ secrets.APPLICATION_YML_GATEWAY }}"
          echo "=== printf (single quote) ==="
          printf "%s\n" '${{ secrets.APPLICATION_YML_GATEWAY }}'
          echo "=== END OF PRINTF ==="
        shell: bash

      # 3. heredoc으로 바로 출력
      - name: heredoc cat secret value
        run: |
          echo "=== heredoc ==="
          cat <<EOF
          ${{ secrets.APPLICATION_YML_GATEWAY }}
          EOF
          echo "=== END OF HEREDOC ==="
        shell: bash

      # 4. echo로 파일 저장
      - name: Save application.yml with echo
        run: |
          mkdir -p ./gateway/src/main/resources
          echo "${{ secrets.APPLICATION_YML_GATEWAY }}" > ./gateway/src/main/resources/application_echo.yml
        shell: bash

      # 5. printf로 파일 저장
      - name: Save application.yml with printf
        run: |
          printf '%s\n' "${{ secrets.APPLICATION_YML_GATEWAY }}" > ./gateway/src/main/resources/application_printf.yml
        shell: bash

      # 6. heredoc으로 파일 저장
      - name: Save application.yml with heredoc
        run: |
          mkdir -p ./gateway/src/main/resources
          cat <<EOF > ./gateway/src/main/resources/application_heredoc.yml
          ${{ secrets.APPLICATION_YML_GATEWAY }}
          EOF
        shell: bash

      # 7. echo로 저장한 파일 cat
      - name: cat application_echo.yml
        run: |
          echo "=== application_echo.yml ==="
          cat ./gateway/src/main/resources/application_echo.yml
          echo "=== END ==="
        shell: bash

      # 8. printf로 저장한 파일 cat
      - name: cat application_printf.yml
        run: |
          echo "=== application_printf.yml ==="
          cat ./gateway/src/main/resources/application_printf.yml
          echo "=== END ==="
        shell: bash

      # 9. heredoc으로 저장한 파일 cat
      - name: cat application_heredoc.yml
        run: |
          echo "=== application_heredoc.yml ==="
          cat ./gateway/src/main/resources/application_heredoc.yml
          echo "=== END ==="
        shell: bash
